name: php-build
run-name: ${{ github.actor }} is building new app version
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - run: php hello.php
      - name: Recuperar una variable secreta
        env:
          MY_SECRET: ${{ Secrets.PROVA_SECRET }}
        run: echo $MY_SECRET
